### ISSUE TITLE
Add CoProtector Method Implementation

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDPoisoner#22]
**Tasks**

- [ ] 1. Implement the CoProtector Method (paper - [CoProtector: Protect Open-Source Code against Unauthorized Training Usage with Data Poisoning](https://arxiv.org/pdf/2110.12925.pdf) )
- [ ] 2. Add sample input data in test folder
- [ ] 3. Provide testing script to run with sample data
- [ ] 4. Add Dockerfile

**Comment by nitesh31mishra** [comment]
Details:
- Currently look for `.java` files as input.
- Works only for `code_corrupting` technique as of now.

Added the testing script as well to run with sample input data.

**Comment by nitesh31mishra** [comment]
- Now code accepts the `.jsonl` files as input.
