### ISSUE TITLE
Add BADCODE Method Implementation

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDPoisoner#23]
**Tasks**

- [ ] Implement the BADCODE Method - paper [Backdooring Neural Code Search](https://arxiv.org/pdf/2305.17506.pdf)
- [ ] Add sample input data in test folder for your method.
- [ ] Provide testing script in `test/method` folder which runs with the above sample data.
- [ ] Add Dockerfile for your method.
- [ ] Method Integrated Completely - Running State.

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to those issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file structure information.

**Comment by nitesh31mishra** [comment]
Integrated on main!
