### ISSUE TITLE
Add CodeBert Backdoor Method Implementation

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDPoisoner#24]
**Tasks**

- [x] Implement the CodeBert Backdoor Method - paper: [You See What I Want You to See: Poisoning Vulnerabilities in Neural Code Search](https://yuleisui.github.io/publications/fse22a.pdf)
- [x] Add sample input data in test folder for your method.
- [x] Provide testing script in `test/method` folder which runs with the above sample data.
- [x] Add Dockerfile for your method.
- [x] Method Integrated Completely - Running State.
- [ ] Get the approval on this implemented method from original authors of the paper. 

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to those issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file structure information.

**Comment by nitesh31mishra** [comment]
Integrated to main!

**Comment by adityabasarkar** [comment]
I'm unable to access the GPUs from inside docker containers. Can you install the NVIDIA Container Toolkit to allow Docker to utilize the GPU?

**Comment by nitesh31mishra** [comment]
Hey @adityabasarkar I just installed the NVIDIA Container Toolkit, let me know if I need to install anything else.
