### ISSUE TITLE
Add AFRAIDOOR Method Implementation

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDPoisoner#25]
**Tasks**

- [x] Implement the AFRAIDOOR Method - paper: [Stealthy Backdoor Attack for Code Models](https://arxiv.org/pdf/2301.02496.pdf)
- [x] Add sample input data in test folder for your method.
- [x] Provide testing script in `test/method` folder which runs with the above sample data.
- [ ] Add Dockerfile for your method.
- [x] Method Integrated Completely - Running State.
- [ ] Get the approval on this implemented method from original authors of the paper. 

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to those issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file structure information.

**Comment by nitesh31mishra** [comment]
Failing when system looks for python3 instead of python

**Comment by nitesh31mishra** [comment]
Fixed the bug with above PR
